[versions]
javalin = "6.3.0"
jackson = "2.17.2"
logback = "1.5.12"

[libraries]
javalin = { group = "io.javalin", name = "javalin", version.ref = "javalin" }
jackson_databind = { group = "com.fasterxml.jackson.core", name = "jackson-databind", version.ref = "jackson" }
logback = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback" }
