[versions]
javalin = "6.3.1-SNAPSHOT"
jackson = "2.17.2"
logback = "1.5.12"

idea_ext = "1.1.9"

[libraries]
javalin = { group = "io.javalin", name = "javalin", version.ref = "javalin" }
jackson_databind = { group = "com.fasterxml.jackson.core", name = "jackson-databind", version.ref = "jackson" }
logback = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback" }

[plugins]
idea_ext = { id = "org.jetbrains.gradle.plugin.idea-ext", version.ref = "idea_ext" }